# ===============================
# = Spring Profiles
# ===============================
spring:
  profiles:
    active: default
    locale: en

# ===============================
# = Server Ports.
# ===============================
server:
  port: 8700

# ===============================
# = Springdoc (Swagger/OpenAPI)
# ===============================
springdoc:
  swagger-ui:
    enabled: true

# ===============================
# = Actuator / Health Probes
# ===============================
management:
  server:
    port: 9000  # Dedicated Actuator port for all environments

  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus,livenessProbe,readinessProbe

  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
    diskSpace:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}
      profile: ${spring.profiles.active:default}
