# ===============================
# = Spring Doc
# ===============================
springdoc:
  version: 1.5.13
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /test/index.html
    operationsSorter: method
    enabled: true

  group-configs:
  - group: v1-departing
    produces-to-match: application/vnd.flipfoundry.depart.v1+json
    packages-to-scan: com.flipfoundry.tutorial.application.web.controller
  - group: v1-greeting
    produces-to-match: application/vnd.flipfoundry.greeting.v1+json
    packages-to-scan: com.flipfoundry.tutorial.application.web.controller
  - group: v2-greeting
    produces-to-match: application/vnd.flipfoundry.greeting.v2+json
    packages-to-scan: com.flipfoundry.tutorial.application.web.controller