# ===============================
# = Spring Profiles
# ===============================
spring:
  profiles:
    active: default
    locale: en

# ===============================
# = Server Ports.
# ===============================
server:
  port: 8700
